ALTER TABLE vitals ADD COLUMN IF NOT EXISTS recorded_by UUID REFERENCES staff_users(id);
ALTER TABLE vitals ADD COLUMN IF NOT EXISTS edited_by UUID REFERENCES staff_users(id);
ALTER TABLE vitals ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;
ALTER TABLE vitals ADD COLUMN IF NOT EXISTS deleted_by UUID REFERENCES staff_users(id);
ALTER TABLE vitals ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE vitals ADD COLUMN IF NOT EXISTS edit_log JSONB DEFAULT '[]'::jsonb;
