import sys
lines = open(sys.argv[1], 'r').readlines()
# Insert the doctors clinical notes tab after line 1031
dcn = [
    '\n',
    '      {/* Doctors Clinical Notes Tab */}\n',
    "      {activeSection === 'doctor_clinical_notes' && (\n",
    '        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5">\n',
    '          <div className="flex items-center justify-between mb-4">\n',
    '            <h2 className="text-sm font-semibold text-slate-700">Doctors Clinical Notes</h2>\n',
    '            {isDoctor && (\n',
    "              <button onClick={() => { setShowDoctorNoteModal(true); setDoctorNoteContent(''); setDoctorNoteType('clinical') }}\n",
    '                className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary text-white text-xs font-medium hover:scale-[1.01] transition-transform"><Stethoscope size={14} /> New Note</button>\n',
    '            )}\n',
    '          </div>\n',
    '          {doctorNotes.length === 0 && soapEncounters.length === 0 ? (\n',
    '            <p className="text-sm text-slate-400 text-center py-8">No doctor clinical notes recorded</p>\n',
    '          ) : (\n',
    '            <div className="space-y-4">\n',
    '              {doctorNotes.length > 0 && (\n',
    '                <div className="space-y-3 mb-4">\n',
    '                  <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Written Notes</p>\n',
    '                  {usePagination(doctorNotes, notePage).items.map((n: any) => (\n',
    '                    <div key={n.id} className="p-4 rounded-xl bg-slate-50 border border-slate-100">\n',
    '                      <div className="flex items-center justify-between mb-2 text-xs text-slate-400">\n',
    "                        <span>{new Date(n.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>\n",
    '                        {n.staff_name && <span>by <strong>{n.staff_name}</strong></span>}\n',
    '                      </div>\n',
    '                      <p className="text-sm text-slate-700 whitespace-pre-wrap">{n.content}</p>\n',
    '                    </div>\n',
    '                  ))}\n',
    '                </div>\n',
    '              )}\n',
    '              {soapEncounters.length > 0 && (\n',
    '                <div className="space-y-3">\n',
    '                  <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">SOAP Notes from Encounters</p>\n',
    '                  {soapEncounters.slice(0, 15).map((enc: any) => {\n',
    '                    const soap = enc.soap_notes ? (typeof enc.soap_notes === "string" ? JSON.parse(enc.soap_notes) : enc.soap_notes) : null\n',
    '                    const doctorName = enc.staff_id ? staffCache[enc.staff_id] : null\n',
    '                    const diagnoses = enc.diagnoses ? (Array.isArray(enc.diagnoses) ? enc.diagnoses : typeof enc.diagnoses === "string" ? JSON.parse(enc.diagnoses) : []) : []\n',
    '                    return (\n',
    '                      <div key={enc.id} className="p-4 rounded-xl bg-slate-50 border border-slate-100">\n',
    '                        <div className="flex items-center justify-between mb-2 text-xs text-slate-400">\n',
    '                          <div className="flex items-center gap-2">\n',
    '                            <Stethoscope size={13} className="text-primary" />\n',
    '                            <span className="font-semibold text-slate-700 uppercase text-[10px]">{enc.encounter_type}</span>\n',
    '                          </div>\n',
    '                          <div className="flex items-center gap-2">\n',
    "                            <span>{new Date(enc.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>\n",
    '                            {doctorName && <span>by <strong>{doctorName}</strong></span>}\n',
    '                          </div>\n',
    '                        </div>\n',
    '                        {diagnoses.length > 0 && (\n',
    '                          <div className="flex flex-wrap gap-1.5 mb-2">\n',
    '                            {diagnoses.map((d: any, i: number) => (\n',
    '                              <span key={i} className="px-2 py-0.5 rounded bg-blue-100 text-blue-700 text-[10px] font-medium">{d.code} {d.label?.slice(0, 40)}</span>\n',
    '                            ))}\n',
    '                          </div>\n',
    '                        )}\n',
    '                        {soap && (\n',
    '                          <div className="grid grid-cols-2 gap-3 mt-2">\n',
    "                            {['subjective', 'objective', 'assessment', 'plan', 'notes'].filter((f) => soap[f]).map((f) => (\n",
    '                              <div key={f} className="bg-white rounded-lg p-2.5 border border-slate-100">\n',
    "                                <p className=\"text-[10px] font-medium text-primary capitalize mb-0.5\">{f === 'notes' ? 'Notes' : f}</p>\n",
    '                                <p className="text-sm text-slate-600">{soap[f]}</p>\n',
    '                              </div>\n',
    '                            ))}\n',
    '                          </div>\n',
    '                        )}\n',
    '                      </div>\n',
    '                    )\n',
    '                  })}\n',
    '                </div>\n',
    '              )}\n',
    '            </div>\n',
    '          )}\n',
    '        </div>\n',
    '      )}\n',
]
for i, l in enumerate(dcn):
    lines.insert(1032 + i, l)
open(sys.argv[1], 'w').writelines(lines)
print(f'Inserted {len(dcn)} lines. Total: {len(lines)}')
